name: Terraform AWS Labs

on:
  push:
    branches:
      - main          # Apply ou Destroy só acontece quando há push/merge na main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply or Destroy
        run: |
          if [[ "${GITHUB_REF_NAME}" == "destroy" ]]; then
            echo "Rodando terraform destroy..."
            terraform destroy -auto-approve
          else
            echo "Rodando terraform apply..."
            terraform apply -auto-approve
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Comment on Issue #1
        run: |
          if [[ "${GITHUB_REF_NAME}" == "destroy" ]]; then
            gh issue comment 1 --body "Todos os recursos do lab foram destruídos na AWS (branch destroy mergeada na main)."
          else
            gh issue comment 1 --body "Lab aplicado com sucesso na AWS a partir da branch main."
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
