name: Terraform AWS Deploy

on:
  push:
    branches:
      - "*"   # qualquer branch ativa o workflow

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: Comment on Issue (opcional)
        if: github.event_name == 'push'
        run: |
          gh issue comment 1 --body "Lab aplicado com sucesso no branch ${{ github.ref_name }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
