name: Terraform AWS Labs

on:
  push:
    branches:
      - main          # Apply ou Destroy só acontece quando há push/merge na main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Determine Action from Commit Message
        id: action
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MSG"
          
          if [[ "$COMMIT_MSG" == *"[destroy]"* ]] || [[ "$COMMIT_MSG" == *"destroy"* ]]; then
            echo "action=destroy" >> $GITHUB_OUTPUT
            echo "Ação detectada: DESTROY"
          else
            echo "action=apply" >> $GITHUB_OUTPUT
            echo "Ação detectada: APPLY"
          fi

      - name: Terraform Plan
        run: |
          if [ "${{ steps.action.outputs.action }}" == "destroy" ]; then
            echo "📋 Planejando destruição de recursos..."
            terraform plan -destroy -out=tfplan
          else
            echo "📋 Planejando criação/atualização de recursos..."
            terraform plan -out=tfplan
          fi

      - name: Terraform Apply/Destroy
        run: |
          if [ "${{ steps.action.outputs.action }}" == "destroy" ]; then
            echo "🔥 Destruindo recursos..."
            terraform apply -auto-approve tfplan
          else
            echo "🚀 Aplicando recursos..."
            terraform apply -auto-approve tfplan
          fi

      - name: Comment on Issue #1
        run: |
          if [ "${{ steps.action.outputs.action }}" == "destroy" ]; then
            gh issue comment 1 --body "🔥 **Recursos destruídos com sucesso!**
            
            Todos os recursos do lab foram removidos da AWS.
            
            **Commit:** ${{ github.event.head_commit.message }}
            **SHA:** ${{ github.sha }}"
          else
            gh issue comment 1 --body "🚀 **Lab aplicado com sucesso!**
            
            Recursos criados/atualizados na AWS.
            
            **Commit:** ${{ github.event.head_commit.message }}
            **SHA:** ${{ github.sha }}"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}